webapp/items/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name='items'

import time
urlpatterns = [
	
	url('home/',views.index,name='index'),
	url('login/',views.UserFormView.as_view(),name= 'login'),
	url('logout/',views.logout_view,name = 'logout'),
	url('create/',views.CreateItemView.as_view(),name='create'),
	url('map/',views.map,name='map'),
	path('details/<itemname>/',views.detail,name='detail'),
	path('details/<itemname>/checks/',views.checked , name = 'checked'),
	path('users-details/<username>/',views.user_detail,name='user_detail'),
	path('send/<itemname>/',views.send,name = 'send')

]

webapp/profiles/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name='profiles'

import time
urlpatterns = [
	url('home/',views.index,name='home'),
	url('create/',views.CreateProfileView.as_view(),name='create'),
	path('details/<username>/',views.detail,name='detail'),

]

webapp/webapp/urls.py
from django.contrib import admin
from django.conf.urls import url,include

urlpatterns = [
    url('admin/', admin.site.urls),
    url('items/',include('items.urls')),
    url('profiles/',include('profiles.urls')),
    url('ptypes/', include('ptypes.urls'))
]

webapp/items/models.py
# Models that are required for forms to be made. These are used in forms.py and views.py

from django.db import models

# Create your models here.
class Item(object):
	def __init__(self,name,check,c_addr,p_addr):
		self.name = name
		self.check = check
		self.c_addr = c_addr
		self.p_addr = p_addr

class history_object(object):
    def __init__(self,name,action,c_addr,p_addr,timestamp):
        self.name = name
        self.action = action
        self.c_addr = c_addr
        self.p_addr = p_addr
        self.timestamp = timestamp


class ItemCreation(models.Model):
    itemname = models.CharField(max_length=30)
    password = models.CharField(max_length=30)
    ptype = models.CharField(max_length=30)

class ItemSending(models.Model):
    recv = models.CharField(max_length = 30)
    password = models.CharField(max_length=30)


class userinfo(object):

    def __init__(self,name,lat,longi,iheld=None):

        self.name = name
        self.lat = lat
        self.longi = longi
        if iheld == None:
            self.iheld = 1
        else:
            self.iheld = iheld
        

webapp/items/forms.py
# Forms that are created with the help of models.py. These forms are used in views.py and rendered in the corresponding HTML pages

from django.contrib.auth.models import User
from django import forms
from .models import ItemCreation
from .models import ItemSending

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ['username','email','password']


#Create a form for creation of item
#Code reuse :D

#probably will hit me 
class CreateItemForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)

	class Meta:
		model = ItemCreation
		fields = ['itemname','password','ptype']

class SendItemForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)

	class Meta:
		model = ItemSending
		fields = ['recv','password']

webapp/items/views.py
# Each method corresponds to an HTML page within the templates folder of the same name

from django.shortcuts import render,redirect
from django.http import Http404
from django.contrib.auth import authenticate, login , logout
from .sawtooth import querying
from .sawtooth import send as send_saw
from .sawtooth import create as create_saw
from .sawtooth import finder as finder_saw
from .sawtooth import his
from .sawtooth import checks,forwarding
from profiles.wallet import finder as finder_wal
from .forms import UserForm,SendItemForm
from .forms import CreateItemForm
from django.views import View
from .models import userinfo
import json



###IMPORTANT SEND ALL DESERIALS TO RESPECTIVE MODULES
##configure randomness here
## write a module that reads from servers.json or some other and uses it herre (sort of like config file)
def random_server():
	urls_list = { '1': 'http://127.0.0.1:8008','2': 'http://rest-api-0:8008' }
	return urls_list['2']

def index(request):
	
	if request.user.is_authenticated == False :
		return redirect('items:login')
	url = random_server()

	if not request.GET.get('q'):
		resp= querying.query_user_held(request.user.username,url)
		flag = 1
		#returns from state table all the datas with c_add as username
	else:
		resp = querying.query_possible_items(request.GET.get("q"),url)
		flag = 0
		#flag to stop having the username in the html
		#takes care of search form
		
	# for name,item_obj in resp.items():
	# 	#finding out human name of the public key holder
	# 	nc_add = finder_wal.query(item_obj.c_addr,request.user.username,url)
	# 	nc_add = _deserialize_key(nc_add)
	# 	resp[name].c_addr = nc_add.name

	context = {'resp' :resp, 'username' : request.user.username,'flag' : flag}

	return render(request,'items/index.html', context)

# detail page for each item name that sates which checks have been completed and handling history
# allows the user to send the item to the next user
def detail(request,itemname):
	
	if request.user.is_authenticated == False :
		return redirect('items:login')
	url = random_server()


	#find item uses state list
	# finding the details of itemname in the state database 
	resp = finder_saw.find(itemname,'ubuntu',url)
	

	# nc_add is the human readable name
	nc_add = finder_wal.query(resp[itemname].c_addr,'ubuntu',url)
	# breaking apart the string with commas
	user_profile = _deserialize_key(nc_add)

	nc_add = user_profile.name


	# finding the profile 

	user_profile = finder_wal.query(nc_add,'ubuntu',url)
	user_profile = _deserialize_key(user_profile)
	resp[itemname].c_addr = nc_add
	#get the checks list
	checks_list = checks.item_checks_list(check_status = resp[itemname].check,profile =user_profile.profile)
	#hist goes through transactions in block chain, so returns in human readble form
	
	#serialized make that into an item history class with all the attributes so that django 
	#will not complain
	#we can do the serializtion and breaking up stuff in the his.py

	# looks through all the transactions to find history
	hist= his.item_history(itemname,url)
	requested_user = request.user.username
	

	# submit button is only shown in the current address of the item is the same as the current user of the page. 
	context = {'resp' :resp,'hist' : hist , "checks_list" : checks_list , 'requested_user':requested_user }

	return render(request,'items/detail.html',context)	

def user_detail (request,username):

	if request.user.is_authenticated == False :
		return redirect('items:login')

	url = random_server()

	if not request.GET.get('q'):
		resp= querying.query_user_held(username,url)
		#returns from state table all the datas with c_add as username
	else:
		resp = querying.query_possible_items(request.GET.get("q"),url)
		#takes care of search form
		
	for name,item_obj in resp.items():
		#finding out human name of the public key holder
		######HERE TOOOO
		nc_add = finder_wal.query(item_obj.c_addr,request.user.username,url)
		nc_add = _deserialize_key(nc_add).name
		resp[name].c_addr = nc_add


	context = {'resp' :resp,'username':username}

	return render(request,'items/user-detail.html', context)
	






def checked(request,itemname):


	if request.user.is_authenticated == False :
		return redirect('items:login')

	url = random_server()


	response_url = checks.check(itemname, request.user.username,request.POST['check'],request.user.username,url)

	
	resp = finder_saw.find(itemname,'ubuntu',url)
	
	nc_add = finder_wal.query(resp[itemname].c_addr,'ubuntu',url)
	user_profile = _deserialize_key(nc_add) 
	nc_add = user_profile.name
	user_profile = finder_wal.query(nc_add,'ubuntu',url)
	user_profile = _deserialize_key(user_profile)
	resp[itemname].c_addr = nc_add
	#get the checks list
	checks_list = checks.item_checks_list(resp[itemname].check,user_profile.profile)
	#hist goes through transactions in BC, so returns in human readble form
	hist= his.item_history(itemname,url)
	requested_user = request.user.username
	context = {'resp' :resp,'hist' : hist , "checks_list" : checks_list,'requested_user':requested_user}
	return render(request,'items/detail.html',context)

# class SendItem(View):
# 	form_class = SendItemForm
# 	template_name = 'items/send.html'

# 	def get(self,request,itemname):

# 		if request.user.is_authenticated == False :
# 			return redirect('items:login')

# 		url = random_server()
# 		form = self.form_class(None)
# 		#can change 'ubuntu' to 'requested user'
# 		resp = finder_saw.find(itemname,'ubuntu',url)
	
# 		nc_add = finder_wal.query(resp[itemname].c_addr,'ubuntu',url)
# 		user_profile = _deserialize_key(nc_add) 
# 		nc_add = user_profile.name
# 		user_profile = finder_wal.query(nc_add,'ubuntu',url)
# 		user_profile = _deserialize_key(user_profile)
# 		resp[itemname].c_addr = nc_add
# 		#get the checks list
# 		checks_list = checks.item_checks_list(resp[itemname].check,user_profile.profile)
# 		#hist goes through transactions in block chain, so returns in human readble form
		
# 		#serialized make that into an item history class with all the attributes so that django 
# 		#will not complain
# 		#we can do the serializtion and breaking up stuff in the his.py
# 		hist= his.item_history(itemname,url)
# 		requested_user = request.user.username

# 		context = {'form' : form,'itemname' : itemname ,'resp' :resp,'hist' : hist , "checks_list" : checks_list , 'requested_user':requested_user}

# 		return render(request,self.template_name,context)

# 	def post(self,request,itemname):

# 		if request.user.is_authenticated == False :
# 			return redirect('items:login')
# 		url = random_server()
# 		# username = request.user.username
# 		# password  =request.POST['password']
# 		# user = authenticate(username=username,password=password)
# 		user = request.user.username
# 		if user is not None:
# 			send.snd(itemname,forwarding.from_user(request.user.username),request.user.username,url) 
# 			#time.sleep(1.5)
# 			return redirect('items:index')
# 		else:
# 			#retry password
# 			form = self.form_class(None)
# 			return render(request,self.template_name,{'form' : form})


def send(request,itemname):
	
	if request.user.is_authenticated == False :
		return redirect('items:login')
	url = random_server()

	send_saw.snd(itemname,forwarding.from_user(request.user.username),request.user.username,url)

	#find item uses state list 
	resp = finder_saw.find(itemname,'ubuntu',url)
	
	#######VERY IMPOSRTANT CHANGE TO BE APPLIED HERE TOOO
	nc_add = finder_wal.query(resp[itemname].c_addr,'ubuntu',url)
	user_profile = _deserialize_key(nc_add) 
	nc_add = user_profile.name
	user_profile = finder_wal.query(nc_add,'ubuntu',url)
	user_profile = _deserialize_key(user_profile)
	resp[itemname].c_addr = nc_add
	#get the checks list
	checks_list = checks.item_checks_list(check_status = resp[itemname].check,profile =user_profile.profile)
	#hist goes through transactions in block chain, so returns in human readble form
	
	#serialized make that into an item history class with all the attributes so that django 
	#will not complain
	#we can do the serializtion and breaking up stuff in the his.py
	hist= his.item_history(itemname,url)
	requested_user = request.user.username

	

	context = {'resp' :resp,'hist' : hist , "checks_list" : checks_list , 'requested_user':requested_user,'sent_to':forwarding.from_user(request.user.username) }
	return render(request,'items/send.html',context)	





def map(request):
	
	if request.user.is_authenticated == False :
		return redirect('items:login')

	url =random_server()
	#GeoLocations of users Probably change this entire charade to some other file ????
	locations = {'admin':{'lat' : 42.34, 'longi' : -71.55},'Larry@lab':{'lat':42.34, 'longi': -71.64}, 'Mike@manufacturing':{'lat':42.342, 'longi' : -71.52}, 'Susan@sterilization':{'lat':42.339 , 'longi': -71.53}, 'Quinn@quality':{'lat':42.39 , 'longi': -71.54}}
	
	
	
	response = querying.query_all_items(url)
	resp = {}
	usersdata = {}
	for s in response:
		name,checks,c_add,prev_add = response[s].decode().split(",")
		try:
			nc_add = finder_wal.query(c_add,'ubuntu',url)
			nc_add = _deserialize_key(nc_add).name
			resp[name] = Item(name,checks,nc_add,prev_add)
			
			try:
				usersdata[nc_add].iheld += 1
			except:
				usersdata[nc_add] = userinfo(nc_add,float(locations[nc_add]['lat']),float(locations[nc_add]['longi']))
		except:
			pass	


	
	context = {'resp' :resp , 'usersdata' : usersdata}
	return render(request,'items/map.html', context)


class CreateItemView(View):

	form_class = CreateItemForm
	template_name = 'items/create.html'

	def get(self,request):

		if request.user.is_authenticated == False :
			return redirect('items:login')

		form = self.form_class(None)
		return render(request,self.template_name,{'form' : form})


	def post(self,request):
		
		if request.user.is_authenticated == False :
			return redirect('items:login')
		url = random_server()

		itemname = request.POST['itemname']
		username = request.user.username
		password  =request.POST['password']

webapp/items/templates/items/base.html
<!DOCTYPE html>
<!--Is my Windows working?-->
<html lang="en">
<head>
    <style>
        html,body{height: 100%;}

    </style>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta charset="UTF-8">
    <title>{% block title %}Active Release{% endblock %}</title>
    {% load staticfiles %}
    {% block imports %}{% endblock %}
   
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    
</head>

<body style="background-color:rgba(235, 232, 232, 0.979);overflow:auto" >

<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'items:index' %}">Active Release</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'items:map' %}"><span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>&nbsp; Activity Stream</a></li>
            </ul>

        <!-- Search -->
        <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'items:index' %}">
            <div class="form-group">
                <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
            </div>
            <button type="submit" class="btn btn-default">Search</button>
        </form>


            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'profiles:home' %}">
                            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Admin
                        </a>

                </li>
                <li>
                    <a href="{% url 'items:create' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Create
                    </a>
                </li>
                <li>
                    <a href="{% url 'items:logout' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

webapp/items/templates/items/create.html
{% extends 'items/base.html' %}
{% block title %} Create item {% endblock %}



{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Create Item</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'items:create'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_itemname">
                                Name of the Item
                            </label>
                            <div class="col-sm-10">
                                <input id="id_itemname" maxlength="30" name="itemname" type="text">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_ptype">
                                Product Type of the Item
                            </label>
                            <div class="col-sm-10">
                                <input id="id_ptype" maxlength="30" name="ptype" type="text">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>



{{ form.errors }}
{{ form.non_field_errors }}

{% endblock %}

webapp/items/templates/items/detail.html
{% extends 'items/base.html' %}
{% block title %}Details{% endblock %}
{% block body %}
	<div class= "container">
	<div id="checks_text" style="margin: 0 auto; float: left; "><ul>

		
		
		{% for item,g in resp.items %}
			<h3>Requirements of {{ g.name }}</h3>
			<h6><a href= "{% url 'items:detail' g.name %}">Refresh</a></h6>

			<h5>Currently with {{ g.c_addr }}</h5>
			
			<form action="{% url 'items:checked' g.name %}" method="post">

				{% csrf_token %}
				
				{% for checkno,obj in checks_list.items %}

					{% if forloop.counter == 1 %}
					<h4>Manufacturing Site QA</h4>
					{% endif %}
					{% if forloop.counter == 5 %}
					<br><h4>Sterilization Unit</h4>
					{% endif %}
					{% if forloop.counter == 7 %}
					<br><h4>Distribution Centre - QA</h4>
					{% endif %}



					{% if obj.check %}
						{% if obj.auth%}
							<input type="checkbox" name="check" value="{{ forloop.counter }}" /><label>{{ obj.name }}</label><br>			
						{% else %}
						<input type="checkbox" name="check" disabled="disabled" value="{{ forloop.counter }}" />
							<label style = "color:grey">{{ obj.name }}</label><br>			
						{% endif %}

					{% else %}
					<input type="checkbox" name="check" disabled="disabled" value="{{ forloop.counter }}" checked />
						<label style="color:green">{{ obj.name }}</label><br>
					{% endif %}
				
				{% endfor %}
			{% if g.c_addr == requested_user  %}
			<input type = "submit" value="Submit">
			{% endif %}	
			
		</form><br>

		{% if g.c_addr == requested_user %}
		<h4><a href="{% url 'items:send' g.name %}">Send item ?</a></h4><br>
		{% endif %}
		{% endfor %}
	</ul></div>
		

		<!--- Mike at manufacturing send   -->

	<div id="history_text" style="margin:0px auto;float:right; position:relative;"><ul>
		<h3>Previous Transactions</h3>
		<!--its actually next addr in the transactions , please go and look at send in sawtooth folder(inside item)-->
		{% for item,g in hist.items %}
			{% if g.action == 'send'%}
			<li>{{g.c_addr}}: {{g.action}} to  {{g.p_addr}}  at {{g.timestamp}}   </li>
			{% else %}
			<li>{{g.c_addr}}: {{g.action}} at {{g.timestamp}}</li>
			
			{% endif %}

		{% endfor %}
	</ul></div>
	</div>
	
{% endblock %}
<!---href="{% url 'items:detail' object.name %}"-->

webapp/items/templates/items/index.html
{% extends 'items/base.html' %}

{% block body %}
	<div class="container">
	{% if flag == 1 %}
	<h3>Assigned to {{ username }}</h3>
	{% endif %}
	<ul>
		
		{% for name,g in resp.items %}

			<li><a href = "{% url 'items:detail' g.name %} "> {{ g.name }}  is currently with {{ g.c_addr }} </a></li><br>
		{% endfor %}
	</ul>
	</div>
{% endblock %}

webapp/items/templates/items/login_form.html
{% extends 'items/base.html' %}
{% block title %} LOGIN {% endblock %}


{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'items:login'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>


{% endblock %}

webapp/items/templates/items/map.html
{% extends 'items/base.html' %}
{% block title %}Map of All{% endblock %}
{% block imports %}
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css" integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ==" crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js" integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw==" crossorigin=""></script>
{% endblock %}



{% block body %}

	<div id="text" style="float:left;overflow: auto;width:30%; height:80%;">
		<h3> Current state of supplychain</h3>
		<ul>
		{% for name,g in resp.items %}
			<li><a href = "{% url 'items:detail' g.name %} "> {{ g.name }}</a>  is currently with <a href = "{% url 'items:user_detail' g.c_addr %}">{{ g.c_addr }}</a> </li><br>
		{% endfor %}

	</ul></div>
	<div style="float:left;overflow : auto;width:20%; height:80% ">
		<h3> Current state of users </h3>
		<ul>
		{% for name,userinfo in usersdata.items %}
			<li><a href = "{% url 'items:user_detail' name %}">{{ name }}</a> currently has {{ userinfo.iheld }} items </li><br>
		{% endfor %}
	</ul>
	</div>

	<div id="mapid" style="width: 50%; height: 70%; float:right; "></div>
	<script>

		
		var mymap = L.map('mapid').setView([42.34, -71.55], 12);

		//The access token stops workig once there are 100,000 map loads


		L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoiZ3V5ZmF3a2VzMSIsImEiOiJjamlmemp3bncwc3ljM3lvY29lcGsydmd5In0.PRVTC56434Jga12ZTqTndA', {
			maxZoom: 18,
			attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, ' +
				'<a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
				'Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
			id: 'mapbox.streets'
		}).addTo(mymap);


		//excess processing is being used
		//revist
		{% for name,userinfo in usersdata.items %}
		

		marker = new L.marker([{{ userinfo.lat }} , {{ userinfo.longi }} ])
			.bindPopup("<b>{{ name }}</b><br />{{ userinfo.iheld }}")
			.addTo(mymap);	
		{% endfor %}

	</script>

{% endblock %}

webapp/items/templates/items/send.html
{% extends 'items/base.html' %}
{% block title %}Sent{% endblock %}
{% block body %}
	<div class= "container">
	<div id="checks_text" style="margin: 0 auto; float: left; "><ul>

		
		
		{% for item,g in resp.items %}
			<h3>Requirements of {{ g.name }}</h3>
			<h6><a href= "{% url 'items:detail' g.name %}">Refresh</a></h6>
			
			<form action="{% url 'items:checked' g.name %}" method="post">

				{% csrf_token %}
				
				{% for checkno,obj in checks_list.items %}

					{% if forloop.counter == 1 %}
					<h4>Manufacturing Site QA</h4>
					{% endif %}
					{% if forloop.counter == 5 %}
					<br><h4>Sterilization Unit</h4>
					{% endif %}
					{% if forloop.counter == 7 %}
					<br><h4>Distribution Centre - QA</h4>
					{% endif %}



					{% if obj.check %}
						{% if obj.auth%}
							<input type="checkbox" name="check" value="{{ forloop.counter }}" /><label>{{ obj.name }}</label><br>			
						{% else %}
						<input type="checkbox" name="check" disabled="disabled" value="{{ forloop.counter }}" />
							<label style = "color:grey">{{ obj.name }}</label><br>			
						{% endif %}

					{% else %}
					<input type="checkbox" name="check" disabled="disabled" value="{{ forloop.counter }}" checked />
						<label style="color:green">{{ obj.name }}</label><br>
					{% endif %}
				
				{% endfor %}
			{% if g.c_addr == requested_user  %}
			<input type = "submit" value="Submit">
			{% endif %}	
			
		</form><br>
        
		<h4><a href="{% url 'items:send' g.name %}">Send item ?</a></h4>
        <h4>Item sent to {{ sent_to }}</h4>
		{% endfor %}
	</ul></div>
		

		<!--- Mike at manufacturing send   -->

	<div id="history_text" style="margin:0px auto;float:right; position:relative;"><ul>
		<h3>Previous Transactions</h3>
		<!--its actually next addr in the transactions , please go and look at send in sawtooth folder(inside item)-->
		{% for item,g in hist.items %}
			{% if g.action == 'send'%}
			<li>{{g.c_addr}}: {{g.action}} to  {{g.p_addr}}  at {{g.timestamp}}   </li>
			{% else %}
			<li>{{g.c_addr}}: {{g.action}} at {{g.timestamp}}</li>
			
			{% endif %}

		{% endfor %}
	</ul></div>
	</div>
	<script>
		alert('Item sent to {{ sent_to }}');
	</script>
	
{% endblock %}
<!---href="{% url 'items:detail' object.name %}"-->

webapp/items/templates/items/user-detail.html
{% extends 'items/base.html' %}

{% block body %}
	<div class="container">
	{% if flag == 1 %}
	<h3>Assigned to {{ username }}</h3>
	{% endif %}
	<ul>
		
		{% for name,g in resp.items %}

			<li><a href = "{% url 'items:detail' g.name %} "> {{ g.name }}  is currently with {{ g.c_addr }} </a></li><br>
		{% endfor %}
	</ul>
	</div>
{% endblock %}