webapp/items/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name='items'

import time
urlpatterns = [
	
	url('home/',views.index,name='index'),
	url('login/',views.UserFormView.as_view(),name= 'login'),
	url('logout/',views.logout_view,name = 'logout'),
	url('create/',views.CreateItemView.as_view(),name='create'),
	url('map/',views.map,name='map'),
	path('details/<itemname>/',views.detail,name='detail'),
	path('details/<itemname>/checks/',views.checked , name = 'checked'),
	path('users-details/<username>/',views.user_detail,name='user_detail'),
	path('send/<itemname>/',views.send,name = 'send')

]

webapp/profiles/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name='profiles'

import time
urlpatterns = [
	url('home/',views.index,name='home'),
	url('create/',views.CreateProfileView.as_view(),name='create'),
	path('details/<username>/',views.detail,name='detail'),

]

webapp/ptypes/urls.py
from django.urls import path
from django.conf.urls import url

from . import views
app_name = 'ptypes'

urlpatterns = [
    url('index/', views.index, name='index'),
    url('create/', views.create, name='create'),
    url('details/<ptype_name>', views.details, name='details'),
    url('delete/<ptype_name>/<role_name>/<check_name>', views.delete, name='delete'),
] 

webapp/webapp/urls.py
from django.contrib import admin
from django.conf.urls import url,include

urlpatterns = [
    url('admin/', admin.site.urls),
    url('items/',include('items.urls')),
    url('profiles/',include('profiles.urls')),
    url('ptypes/', include('ptypes.urls'))
]

webapp/ptypes/models.py
from django.db import models

# Create your models here.

class ProductType(models.Model):
    ptype_name = models.CharField(max_length = 100)
    role_name = models.CharField(max_length = 100)
    check_assign = models.CharField(max_length = 100)

webapp/ptypes/forms.py
from django.contrib.auth.models import User
from django import forms

from .models import ProductType

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        #fields = ['username', 'password', 'dept'] 
        fields = ['username', 'password']

class ProductTypeForm(forms.ModelForm):
    class Meta:
        model = ProductType
        fields = ['ptype_name', 'role_name', 'check_assign']

webapp/ptypes/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.http import Http404
from django.contrib.auth import authenticate, login, logout
from django.views import View
import json

from .forms import UserForm, User, ProductTypeForm
from .product_type import querying, create_product_type, create_role, create_check, delete_product_type, delete_role, delete_check
# remove when done testing
from . import test

def random_server():
	urls_list = { '1': 'http://127.0.0.1:8008','2': 'http://rest-api-0:8008' }
	return urls_list['2']

def index(request):
    if request.user.is_authenticated == False:
        return redirect('items:index')

    url = random_server()
    response = querying.query_all(url)


    username = request.user.username
    dept = username.split("@")
    dept = dept[1]

    # info is a dictionary - key is name of ptype and value is Ptype object
    info = test.retrieve()
    
    # new
    details = {}
    for data in response:
        name, dept, role = response[data].decode().split(",")
        details[name] = Ptype(name, dept, role)

    #context = {'username' : request.user.username, 'resp' : details} 
    context = {'username' : request.user.username, 'resp' : info}
    return render(request, 'ptypes/index.html', context)

def create(request):
    if request.method == "POST":
        form = ProductTypeForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            username = request.user.username
            dept = username.split("@")
            dept = dept[1]
            url = random_server()

            ptype_name = form.cleaned_data['ptype_name']
            role_assign = form.cleaned_data['role_name']
            check_assign = form.cleaned_data['check_assign']

            test.create(name = ptype_name, dept = dept, role = role_assign, check = check_assign) 

            # when form allows individual submissions
            if role_assign is None and check_assign is None:
                create_product_type.create_ptype(name = ptype_name, dept = dept, adminname = username, url = url)
            elif role_assign is not None and check_assign is None:
                create_role.create_role(name = ptype_name, dept = dept, role = role_assign, check = None, adminname = username, url = url)
            elif check_assign is not None:
                create_check.create_check(name = ptype_name, dept = dept, role = role_assign, check = check_assign, adminname = username, url = url)

            submit = "New Product Type Successfully Created"
            context = {'form': form, 'message' : submit}
            return render(request, 'ptypes/create.html', context)
            

    else:
        form = ProductTypeForm()
        context = {'form' : form}
        return render(request, 'ptypes/create.html', context)

def details(request, ptype_name):
    if request.user.is_authenticated == False:
        return redirect('items:index')
    # only retrieve product types for this department
    

    url = random_server()
    # response is a dictionary with one key value pair - key is ptype name, value is Ptype object
    response = querying.query_one(ptype_name, request.user.username, url)
    
    context = {'response' : response}
    #context = {'response' : info}
    return render(request, 'ptypes/details.html', context)

def delete(request, ptype_name, role_name, check_name):
    if request.user.is_authenticated == False:
        return redirect('items:login')

    username = request.user.username
    dept = username.split("@")
    dept = dept[1]
    url = random_server()

    response = querying.query_one(ptype_name, request.user.username, url)

    if role_name == 'none':
        delete_product_type.delete_ptype(name = ptype_name, dept = dept, adminname = username, url = url)
        message = "Product Type Deleted"
    elif check_name == 'none':
        delete_role.delete_role(name = ptype_name, dept = dept, role = role_name, adminname = username, url = url)
        message = "Role Deleted"
    else:
        delete_check.delete_check(name = ptype_name, dept = dept, role = role_name, check = check_name, adminname = username, url = url)
        message = "Check Deleted"

    context = {'response' : response, 'message' : message}
    return render(request, 'ptypes/delete.html', context)



class Ptype(object):
    def __init__(self, ptype_name, dept, role):
        self.name = ptype_name
        self.dept = dept
        self.role = role

webapp/ptypes/templates/ptypes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        html,body{height: 100%;}

    </style>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta charset="UTF-8">
    <title>{% block title %}Active Release{% endblock %}</title>
    {% load staticfiles %}
    {% block imports %}{% endblock %}
   
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    
</head>

<body style="background-color:rgba(235, 232, 232, 0.979);overflow:auto" >

<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'profiles:home' %}">Active Release Dept Admin</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            
        <!-- Search -->
        <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'profiles:home' %}">
            <div class="form-group">
                <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
            </div>
            <button type="submit" class="btn btn-default">Search</button>
        </form>

            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'ptypes:index' %}">
                        <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>&nbsp; Product Types
                    </a>
    
                </li>
                <li>
                    <a href="{% url 'ptypes:create' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Create Product Type
                    </a>
                </li>
                <li>
                    <a href="{% url 'items:logout' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

webapp/ptypes/templates/ptypes/create.html
{% extends 'ptypes/base.html' %}
{% block title %}Create{% endblock %}
{% block body %}
    <div class ="container">
        <h3>Create a Product Type</h3>

        <form method = "POST" action = "{% url 'ptypes:create'%}">
            {% csrf_token %}
            {{form}}
            <button type="submit">Submit</button>
        </form>
        <h4 style="color:green">{{message}}</h4>
    </div>

{% endblock %}

webapp/ptypes/templates/ptypes/delete.html
{% extends 'ptypes/base.html' %}
{% block title %}Delete{% endblock %}
{% block body %}
    <div class ="container">

        {% for ptype,g in response.ptypes %}
            <h3>Product Type Details of {{g.name}}</h3>
            <h6><a href="{% ptypes:delete g.name none none %}">Delete Product Type</a></h6> 
                {% for roles in g.role %}
                    <h4>{{roles}}</h4>
                    <a href="{% ptyes:delete g.name roles none %}">Delete Role</a>
                    <ul>
                        {% for checks in g.role.get(roles)}
                            <li>{{checks}}</li>
                            <a href="{% ptypes:delete g.name roles check %}">Delete Check</a>
                        {% endfor %}
                    </ul>
                {% endfor %}
        
        {% endfor %}
        
    </div>

    <script>
        alert('{{message}}')
    </script>

{% endblock %}

webapp/ptypes/templates/ptypes/details.html
{% extends 'ptypes/base.html' %}

{% block body %}
    <div class ="container">

        {% for ptype,g in response.ptypes %}
            <h3>Product Type Details of {{g.name}}</h3>
            <h6><a href="{% ptypes:delete g.name none none %}">Delete Product Type</a></h6> 
                {% for roles in g.role %}
                    <h4>{{roles}}</h4>
                    <a href="{% ptyes:delete g.name roles none %}">Delete Role</a>
                    <ul>
                        {% for checks in g.role.get(roles)}
                            <li>{{checks}}</li>
                            <a href="{% ptypes:delete g.name roles check %}">Delete Check</a>
                        {% endfor %}
                    </ul>
                {% endfor %}
        
        {% endfor %}
        
    </div>

{% endblock %}

webapp/ptypes/templates/ptypes/index.html
{% extends 'ptypes/base.html' %}

{% block body %}
    <div class ="container">
        <h3>Assigned to {{ username }}</h3>
    </div>

    <ul>
        <!-- {% for ptype in resp.items %}
            <li><a href= "{% url 'ptypes:details' ptype.name %}"> {{ ptype.name }}</a></li>
            <br>
        {% endfor %} -->
        {% for ptype in info.items %}
        <li>{{ ptype.name }}</li>
        {% endfor %}
    </ul>

{% endblock %}