webapp/items/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name='items'

import time
urlpatterns = [
	
	url('home/',views.index,name='index'),
	url('login/',views.UserFormView.as_view(),name= 'login'),
	url('logout/',views.logout_view,name = 'logout'),
	url('create/',views.CreateItemView.as_view(),name='create'),
	url('map/',views.map,name='map'),
	path('details/<itemname>/',views.detail,name='detail'),
	path('details/<itemname>/checks/',views.checked , name = 'checked'),
	path('users-details/<username>/',views.user_detail,name='user_detail'),
	path('send/<itemname>/',views.send,name = 'send')

]

webapp/profiles/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name='profiles'

import time
urlpatterns = [
	url('home/',views.index,name='home'),
	url('create/',views.CreateProfileView.as_view(),name='create'),
	path('details/<username>/',views.detail,name='detail'),

]

webapp/webapp/urls.py
from django.contrib import admin
from django.conf.urls import url,include

urlpatterns = [
    url('admin/', admin.site.urls),
    url('items/',include('items.urls')),
    url('profiles/',include('profiles.urls')),
    url('ptypes/', include('ptypes.urls'))
]

webapp/items/models.py
# Models that are required for forms to be made. These are used in forms.py and views.py

from django.db import models

# Create your models here.
class Item(object):
	def __init__(self,name,check,c_addr,p_addr):
		self.name = name
		self.check = check
		self.c_addr = c_addr
		self.p_addr = p_addr

class history_object(object):
    def __init__(self,name,action,c_addr,p_addr,timestamp):
        self.name = name
        self.action = action
        self.c_addr = c_addr
        self.p_addr = p_addr
        self.timestamp = timestamp


class ItemCreation(models.Model):
    itemname = models.CharField(max_length=30)
    password = models.CharField(max_length=30)
    ptype = models.CharField(max_length=30)

class ItemSending(models.Model):
    recv = models.CharField(max_length = 30)
    password = models.CharField(max_length=30)


class userinfo(object):

    def __init__(self,name,lat,longi,iheld=None):

        self.name = name
        self.lat = lat
        self.longi = longi
        if iheld == None:
            self.iheld = 1
        else:
            self.iheld = iheld
        

webapp/profiles/models.py
from django.db import models

# # Create your models here.
# class ProfileCreation(models.Model):
#     username = models.CharField(max_length=30)
#     password = models.CharField(max_length=30)
#     #profile = models.CharField(max_length=30)

class Pair(object):
	def __init__(self,name,pubkey,prof):
		self.name = name
		self.pubkey = pubkey
		self.prof = prof

class history_object(object):
    def __init__(self,name,action,c_addr,p_addr,timestamp):
        self.name = name
        self.action = action
        self.c_addr = c_addr
        self.p_addr = p_addr
        self.timestamp = timestamp

webapp/profiles/forms.py
from django import forms
#from .models import ProfileCreation

from django.contrib.auth.models import User

class CreateProfileForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ['username','password']

webapp/profiles/views.py
from django.shortcuts import render,redirect
from django.http import Http404
from django.contrib.auth import authenticate, login , logout
from django.views import View
import json
from .wallet import create as create_wal
from .wallet import finder,profile,role_defs
from .forms import CreateProfileForm
from .models import Pair


###WORK on this postponed
def random_server():
	urls_list = { '1': 'http://127.0.0.1:8008','2': 'http://rest-api-0:8008' }
	return urls_list['2']


def index(request):
	
	if request.user.is_staff == False :
		return redirect('items:index')
	#Add group permission instead of just authentication

	url = random_server()
	resp ={}
	response = finder.query_all(url)
	for s in response:
		name,pubkey,prof = response[s].decode().split(",")
		resp[name] = Pair(name,pubkey,prof)

		

	context = {'resp' :resp, 'username' : request.user.username}

	return render(request,'profiles/index.html', context)

def detail(request,username):
	
	if request.user.is_staff == False :
		return redirect('items:index')
	url = random_server()

	hist= finder.user_history(username,url)

	context = {'hist' : hist }
	return render(request,'profiles/detail.html',context)	




class CreateProfileView(View):

	form_class = CreateProfileForm
	template_name = 'profiles/create.html'

	def get(self,request):

		if request.user.is_staff == False :
			return redirect('items:login')

		form = self.form_class(None)
		return render(request,self.template_name,{'form' : form})


	def post(self,request):
		
		if request.user.is_staff == False :
			return redirect('items:login')
		url = random_server()
		form = CreateProfileForm(request.POST)
		
		if form.is_valid():
			user = form.save(commit=False)
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			
			user.set_password(password)
			user.save()
			create_wal.add(username,request.user.username,url)
			df_profs = role_defs.role_prof(username)
			profile.prof(username,df_profs,request.user.username,url)

			return redirect('profiles:home')
		else:
			return redirect('profiles:create')


	
		

webapp/profiles/templates/profiles/base.html
<!DOCTYPE html>
<!--Is my Windows working?-->
<html lang="en">
<head>
    <style>
        html,body{height: 100%;}

    </style>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta charset="UTF-8">
    <title>{% block title %}Active Release{% endblock %}</title>
    {% load staticfiles %}
    {% block imports %}{% endblock %}
   
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    
</head>

<body style="background-color:rgba(235, 232, 232, 0.979);overflow:auto" >

<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'profiles:home' %}">Active Release Admin</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            
        <!-- Search -->
        <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'profiles:home' %}">
            <div class="form-group">
                <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
            </div>
            <button type="submit" class="btn btn-default">Search</button>
        </form>

            <ul class="nav navbar-nav navbar-right">
                <li>
                        <a href="{% url 'items:index' %}">
                                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>&nbsp; Items
                            </a>
    
                    </li>
                <li>
                    <a href="{% url 'profiles:create' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Create User
                    </a>
                </li>
                <li>
                    <a href="{% url 'items:logout' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

webapp/profiles/templates/profiles/create.html
{% extends 'profiles/base.html' %}
{% block title %} Create item {% endblock %}



{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Create a User</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'profiles:create'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_itemname">
                                New User
                            </label>
                            <div class="col-sm-10">
                                <input id="id_itemname" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>



{% endblock %}

webapp/profiles/templates/profiles/detail.html
{% extends 'profiles/base.html' %}
{% block title %}Details{% endblock %}
{% block body %}
	<div class= "container">

		

	<div id="history_text" style="margin:0px auto;float:left; position:relative;"><ul>
		<h3>User Activity</h3>
		<!--its actually next addr in the transactions , please go and look at send in sawtooth folder(inside item)-->
		{% for item,g in hist.items %}
			{% if g.action == 'send'%}
			<li>{{g.c_addr}}: {{g.action}} to  {{g.p_addr}}  at {{g.timestamp}}   </li>
			{% else %}
			<li>{{g.c_addr}}: {{g.action}} at {{g.timestamp}}</li>
			
			{% endif %}

		{% endfor %}
	</ul></div>
	</div>
	
{% endblock %}
<!---href="{% url 'items:detail' object.name %}"-->

webapp/profiles/templates/profiles/index.html
{% extends 'profiles/base.html' %}

{% block body %}
	<div class="container">
	{% comment %} {% if flag == 1 %} {% endcomment %}
	<h3>Assigned to {{ username }}</h3>
	{% comment %} {% endif %} {% endcomment %}
	<ul>
		
		{% for name,g in resp.items %}

			<li><a href = "{% url 'profiles:detail' g.name %} "> {{ g.name }}</a>  has public key of {{ g.pubkey }}</li><br> 
		{% endfor %}
	</ul>
	</div>
{% endblock %}